#ifndef BOOT_CONFIG_H
#define BOOT_CONFIG_H

#include <stdint.h>

#define BOOTLOADER_START_ADDR   0x08000000UL
#define APP_START_ADDR          0x08010000UL
#define FLASH_END_ADDR          0x08080000UL
#define APP_META_ADDR           (FLASH_END_ADDR - 0x10UL)
#define APP_FLASH_END_ADDR      APP_META_ADDR

#define APP_META_MAGIC          0xA5A55A5AUL
#define APP_META_STATE_VALID    0x00000000UL
#define APP_META_STATE_ERASED   0xFFFFFFFFUL

#define SRAM_START_ADDR         0x20000000UL
#define SRAM_SIZE_BYTES         (128UL * 1024UL)
#define SRAM_END_ADDR           (SRAM_START_ADDR + SRAM_SIZE_BYTES)

#define BOOT_MAGIC_VALUE        0xB007C0DEUL

#define BOOTLOADER_VERSION_MAJOR 0x00U
#define BOOTLOADER_VERSION_MINOR 0x01U

#define BOOT_UPDATE_WAIT_MS     500UL

#define CAN_HOST_CMD_ID         0x101U
#define CAN_HOST_DATA_ID        0x102U
#define CAN_HOST_SEQ_DATA_BASE_ID 0x200U
#define CAN_HOST_SEQ_DATA_MASK_ID 0x700U
#define CAN_BOOT_RESP_ID        0x181U

#endif
