#ifndef BOOT_CONFIG_H
#define BOOT_CONFIG_H

#include <stdint.h>

#define BOOTLOADER_START_ADDR   0x08000000UL
#define APP_START_ADDR          0x08010000UL
#define FLASH_END_ADDR          0x08080000UL
#define APP_META_ADDR           (FLASH_END_ADDR - 0x10UL)
#define APP_FLASH_END_ADDR      APP_META_ADDR

#define APP_META_MAGIC          0xA5A55A5AUL
#define APP_META_STATE_VALID    0x00000000UL
#define APP_META_STATE_ERASED   0xFFFFFFFFUL

#define SRAM_START_ADDR         0x20000000UL
#define SRAM_SIZE_BYTES         (128UL * 1024UL)
#define SRAM_END_ADDR           (SRAM_START_ADDR + SRAM_SIZE_BYTES)

#define BOOT_MAGIC_VALUE        0xB007C0DEUL

#define BOOTLOADER_VERSION_MAJOR 0x00U
#define BOOTLOADER_VERSION_MINOR 0x01U

#define BOOT_UPDATE_WAIT_MS     500UL

#ifndef BOOT_NODE_ID
#define BOOT_NODE_ID            0U
#endif

#define BOOT_NODE_ID_MAX        15U

#if BOOT_NODE_ID > BOOT_NODE_ID_MAX
#error "BOOT_NODE_ID must be in range 0..15"
#endif

#define CAN_HOST_CMD_BASE_ID    0x100U
#define CAN_HOST_DATA_BASE_ID   0x110U
#define CAN_BOOT_RESP_BASE_ID   0x180U
#define CAN_HOST_SEQ_DATA_ROOT_ID 0x200U

#define CAN_HOST_CMD_ID         (CAN_HOST_CMD_BASE_ID + BOOT_NODE_ID)
#define CAN_HOST_DATA_ID        (CAN_HOST_DATA_BASE_ID + BOOT_NODE_ID)
#define CAN_BOOT_RESP_ID        (CAN_BOOT_RESP_BASE_ID + BOOT_NODE_ID)

#define CAN_HOST_SEQ_DATA_BASE_ID (CAN_HOST_SEQ_DATA_ROOT_ID + (BOOT_NODE_ID * 0x10U))
#define CAN_HOST_SEQ_DATA_MASK_ID 0x7F0U
#define CAN_HOST_SEQ_DATA_SEQ_MASK 0x0FU

#endif
